### PR TITLE
Minor syntax fixes

### PR DESCRIPTION
**Pull request by mrxinu**
Ruby is awesome. I wish I'd spent more time playing with it. Maybe I can convince a client to let me write an integration in it.

Anyway, on to the pull request! =)

One minor housekeeping fix and one adjustment to the new node properties. Per SolarWinds, none of the default values need to be specified. The only one I'm on the fence about is the caption because the node will be nameless until the first rediscovery runs and currently there's no way to force one via the API.

See the comment from tdanner on my merge to the OrionSDK repo here:
https://github.com/solarwinds/OrionSDK/pull/20#discussion_r51589767

### CODE REVIEW

**Comment by powellnathanj** [comment]
I am not sure what is going on with my notifications, but I did not see this until now.  My sincere apologies.

So, now about the changes, the housekeeping fix is a good catch.  Thank you.

The second change however is deleting documentation.  Those lines are a comment to show the end user what they could sock in their hash to create a node.  Do you still think I should not be showing that because it's misleading folks to think they need all those details?

Thanks for the updates.  I'd like to do a bit more with this library and get it into rubygems.  So thanks for the boost.

**Comment by mrxinu** [comment]
Hey @slaney - no worries on the lag! I totally understand.

You have a good point about the second change and having written some code recently for someone I have realized that without those bits of information you wind up with a lackluster node until the first rediscovery runs. So you're much better off providing that node info upfront when you create it so it at least don't show up without a caption initially.

Maybe have a note indicating which fields are mandatory and which are optional? I think that would do the trick if you want to offer a best practice while still keeping that delineation.

**Comment by powellnathanj** [comment]
That would be awesome.  Are you interested in submitting that? (I figured
out my notifications issues and got an email).

If you're not I will make that change.

Thanks again!

On Thu, Mar 17, 2016 at 4:09 PM, Steven Klassen notifications@github.com
wrote:

> Hey @slaney https://github.com/slaney - no worries on the lag! I
> totally understand.
> 
> You have a good point about the second change and having written some code
> recently for someone I have realized that without those bits of information
> you wind up with a lackluster node until the first rediscovery runs. So
> you're much better off providing that node info upfront when you create it
> so it at least don't show up without a caption initially.
> 
> Maybe have a note indicating which fields are mandatory and which are
> optional? I think that would do the trick if you want to offer a best
> practice while still keeping that delineation.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/slaney/swisclient/pull/1#issuecomment-198062594

## 

Nathan Powell

**Comment by mrxinu** [comment]
I sure will. I think I might have deleted the branch on my end by mistake so I can't adjust it. I'll close this out and submit another pull request.

**Pull request closed without merging**
